### ISSUE TITLE
Skip-gram

### ISSUE THREAD

**Issue by dineshbvadhia** [matiaslaurarasmussen/paragraph2vec#1]
Hi! Not an Issue but curious why CBOW selected over skip-gram for paragraph2vec? Generally, for paragraph2vec (aka doc2vec) skip-gram is recommended - but for word2vec, CBOW+NS gives better results.

**Comment by matt-rocket** [comment]
Hi dineshbvadhia,

I understand your confusion. As you probably can see the paragraph2vec model is actually a word2vec  CBOW model. I abandoned this project halfway to work on an implementation using Theano instead so I kind of forgot all about this project. I believe you are right that the Paragraph Vector (Distributed Memory version) works better. 

Cheers,
Matias

**Comment by dineshbvadhia** [comment]
Hi Matias. Thanks for getting back and explaining the confusion. Is the Theano-based project also on github?
Best ...
Dinesh
